-- A MIDI entry is a historical work; a MIDI file is one binary version of it.
CREATE TABLE midi_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    title TEXT NOT NULL CHECK (length(btrim(title)) > 0),
    description TEXT,
    estimated_year SMALLINT CHECK (estimated_year BETWEEN 1 AND 9999),
    archive_status TEXT NOT NULL DEFAULT 'uncertain'
        CHECK (archive_status IN ('archived', 'partially_recovered', 'lost', 'uncertain')),
    copyright_status TEXT NOT NULL DEFAULT 'unknown'
        CHECK (copyright_status IN ('unknown', 'public_domain', 'licensed', 'copyrighted')),
    license TEXT,
    rights_holder TEXT,
    distribution_permission TEXT NOT NULL DEFAULT 'unknown'
        CHECK (distribution_permission IN ('unknown', 'permission_granted', 'metadata_only', 'restricted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT NOT NULL CHECK (length(btrim(display_name)) > 0),
    biography TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE person_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    alias TEXT NOT NULL CHECK (length(btrim(alias)) > 0),
    UNIQUE (person_id, alias)
);

CREATE TABLE midi_credits (
    midi_id BIGINT NOT NULL REFERENCES midi_entries(id) ON DELETE CASCADE,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
    role TEXT NOT NULL CHECK (role IN ('composer', 'arranger', 'sequencer', 'contributor')),
    PRIMARY KEY (midi_id, person_id, role)
);
CREATE INDEX midi_credits_person_id_idx ON midi_credits (person_id);

CREATE TABLE midi_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    midi_id BIGINT NOT NULL REFERENCES midi_entries(id) ON DELETE CASCADE,
    original_filename TEXT NOT NULL CHECK (length(btrim(original_filename)) > 0),
    sha256 TEXT NOT NULL UNIQUE CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    file_size BIGINT NOT NULL CHECK (file_size > 0),
    storage_key TEXT NOT NULL UNIQUE CHECK (length(btrim(storage_key)) > 0),
    discovered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX midi_files_midi_id_idx ON midi_files (midi_id);

CREATE TABLE historical_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    midi_id BIGINT NOT NULL REFERENCES midi_entries(id) ON DELETE CASCADE,
    website_name TEXT NOT NULL CHECK (length(btrim(website_name)) > 0),
    original_url TEXT,
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    wayback_url TEXT,
    notes TEXT,
    CHECK (first_seen_at IS NULL OR last_seen_at IS NULL OR last_seen_at >= first_seen_at)
);
CREATE INDEX historical_sources_midi_id_idx ON historical_sources (midi_id);

CREATE TABLE recovery_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    midi_id BIGINT NOT NULL REFERENCES midi_entries(id) ON DELETE CASCADE,
    recovered_at TIMESTAMPTZ NOT NULL,
    recovered_by BIGINT REFERENCES people(id) ON DELETE SET NULL,
    story TEXT NOT NULL CHECK (length(btrim(story)) > 0),
    evidence TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX recovery_events_midi_id_idx ON recovery_events (midi_id);
CREATE INDEX recovery_events_recovered_by_idx ON recovery_events (recovered_by);

CREATE FUNCTION set_midi_entry_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER midi_entries_updated_at
BEFORE UPDATE ON midi_entries
FOR EACH ROW EXECUTE FUNCTION set_midi_entry_updated_at();
