-- Retain complete records and relationships in a trash bin for restoration.
ALTER TABLE midi_entries ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE midi_entries ADD COLUMN IF NOT EXISTS deleted_by TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE people ADD COLUMN IF NOT EXISTS deleted_by TEXT;

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('delete', 'restore')),
    entity_type TEXT NOT NULL CHECK (entity_type IN ('midi', 'person')),
    entity_id BIGINT NOT NULL,
    entity_label TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS admin_audit_log_created_at_idx ON admin_audit_log (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS midi_entries_deleted_at_idx ON midi_entries (deleted_at DESC) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS people_deleted_at_idx ON people (deleted_at DESC) WHERE deleted_at IS NOT NULL;
