-- Make provenance comparable and retain small, auditable evidence files.
ALTER TABLE historical_sources
    ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'other'
        CHECK (source_type IN ('original_site', 'forum', 'mailing_list', 'archive', 'search_index', 'personal_collection', 'other')),
    ADD COLUMN IF NOT EXISTS credibility SMALLINT NOT NULL DEFAULT 3
        CHECK (credibility BETWEEN 1 AND 5),
    ADD COLUMN IF NOT EXISTS checked_at TIMESTAMPTZ;

COMMENT ON COLUMN historical_sources.credibility IS
    'Curator assessment from 1 (unverified) to 5 (primary source); not an automated truth score.';

CREATE UNIQUE INDEX IF NOT EXISTS historical_sources_midi_owner_idx ON historical_sources(midi_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS recovery_events_midi_owner_idx ON recovery_events(midi_id, id);

CREATE TABLE IF NOT EXISTS historical_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    midi_id BIGINT NOT NULL REFERENCES midi_entries(id) ON DELETE CASCADE,
    source_id BIGINT,
    recovery_event_id BIGINT,
    original_filename TEXT NOT NULL CHECK (length(btrim(original_filename)) > 0),
    media_type TEXT NOT NULL CHECK (media_type IN ('application/pdf', 'image/jpeg', 'image/png', 'text/plain')),
    sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    file_size INTEGER NOT NULL CHECK (file_size BETWEEN 1 AND 1048576),
    content BYTEA NOT NULL,
    uploaded_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((source_id IS NOT NULL) <> (recovery_event_id IS NOT NULL)),
    UNIQUE (midi_id, sha256),
    CONSTRAINT historical_evidence_source_owner_fk
        FOREIGN KEY (midi_id, source_id) REFERENCES historical_sources(midi_id, id) ON DELETE CASCADE,
    CONSTRAINT historical_evidence_recovery_owner_fk
        FOREIGN KEY (midi_id, recovery_event_id) REFERENCES recovery_events(midi_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS historical_evidence_midi_id_idx ON historical_evidence(midi_id, created_at, id);
