-- Separate staff accounts from archive subjects. Visitors remain anonymous/read-only.
CREATE TABLE IF NOT EXISTS admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE COLLATE "C"
        CHECK (username ~ '^[A-Za-z0-9_.-]{3,64}$'),
    password_hash TEXT,
    role TEXT NOT NULL CHECK (role IN ('super_admin', 'admin')),
    status TEXT NOT NULL CHECK (status IN ('invited', 'active', 'disabled')),
    invitation_hash TEXT UNIQUE CHECK (invitation_hash IS NULL OR invitation_hash ~ '^[0-9a-f]{64}$'),
    invitation_expires_at TIMESTAMPTZ,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'active' AND password_hash IS NOT NULL
            AND password_hash ~ '^pbkdf2_sha256:600000:[0-9a-f]{32}:[0-9a-f]{64}$'
            AND invitation_hash IS NULL AND invitation_expires_at IS NULL)
        OR (status = 'invited' AND password_hash IS NULL
            AND invitation_hash IS NOT NULL AND invitation_expires_at IS NOT NULL)
        OR (status = 'disabled' AND invitation_hash IS NULL AND invitation_expires_at IS NULL)
    )
);

-- Upgrade the installed database account as the initial super administrator.
INSERT INTO admin_users(username, password_hash, role, status)
SELECT username, password_hash, 'super_admin', 'active'
FROM site_installation
WHERE id = 1 AND auth_source = 'database'
ON CONFLICT (username) DO NOTHING;

ALTER TABLE admin_sessions
    ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES admin_users(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS actor_username TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'super_admin'
        CHECK (role IN ('super_admin', 'admin'));
CREATE INDEX IF NOT EXISTS admin_sessions_user_id_idx ON admin_sessions(user_id, expires_at DESC);

CREATE TABLE IF NOT EXISTS admin_invitations (
    token_hash TEXT PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    user_id UUID NOT NULL UNIQUE REFERENCES admin_users(id) ON DELETE CASCADE,
    created_by TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS admin_invitations_expiry_idx ON admin_invitations(expires_at);

CREATE TABLE IF NOT EXISTS admin_user_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT NOT NULL,
    target_user UUID REFERENCES admin_users(id) ON DELETE SET NULL,
    action TEXT NOT NULL CHECK (action IN ('invite', 'accept_invite', 'role_changed', 'disabled')),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS admin_user_audit_created_idx ON admin_user_audit(created_at DESC, id DESC);
