-- Archive contributors are staff users who submit or improve a music entry.
CREATE TABLE midi_contributors (
    midi_id BIGINT NOT NULL REFERENCES midi_entries(id) ON DELETE CASCADE,
    user_id UUID REFERENCES admin_users(id) ON DELETE SET NULL,
    username TEXT NOT NULL,
    first_contributed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_contributed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (midi_id, username)
);
CREATE INDEX midi_contributors_user_idx ON midi_contributors(user_id);

-- Approved staff submissions can be attributed from their original proposer.
INSERT INTO midi_contributors(midi_id,user_id,username,first_contributed_at,last_contributed_at)
SELECT m.id, u.id, r.proposed_by, min(r.created_at), max(r.reviewed_at)
FROM admin_change_requests r
JOIN midi_entries m ON m.id = CASE
    WHEN r.request_type = 'midi.create' AND (r.result->>'id') ~ '^[0-9]+$' THEN (r.result->>'id')::bigint
    ELSE r.entity_id END
LEFT JOIN admin_users u ON u.username = r.proposed_by
WHERE r.status = 'approved' AND r.request_type IN
    ('midi.create','midi.update','credits.update','history.source.create','history.source.update','history.source.delete',
     'history.event.create','history.event.update','history.event.delete','evidence.upload','file.import')
GROUP BY m.id,u.id,r.proposed_by
ON CONFLICT(midi_id,username) DO NOTHING;
INSERT INTO midi_contributors(midi_id,user_id,username,first_contributed_at,last_contributed_at)
SELECT e.midi_id,u.id,e.uploaded_by,min(e.created_at),max(e.created_at)
FROM historical_evidence e LEFT JOIN admin_users u ON u.username=e.uploaded_by
GROUP BY e.midi_id,u.id,e.uploaded_by
ON CONFLICT(midi_id,username) DO NOTHING;

-- Preserve old person-credit data for audit. It cannot be mapped safely to a
-- staff user, so remove it from active musical credits without inventing one.
CREATE TABLE legacy_person_contributor_credits AS
SELECT midi_id,person_id,role,CURRENT_TIMESTAMP AS migrated_at
FROM midi_credits WHERE role='contributor';
DELETE FROM midi_credits WHERE role='contributor';
ALTER TABLE midi_credits DROP CONSTRAINT IF EXISTS midi_credits_role_check;
ALTER TABLE midi_credits ADD CONSTRAINT midi_credits_role_check
    CHECK (role IN ('composer','arranger','sequencer'));

CREATE TABLE useful_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 120),
    url TEXT NOT NULL UNIQUE CHECK (url ~ '^https?://[^[:space:]]+$' AND length(url) <= 4096),
    description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
