"""Optional Playwright browser acceptance; writes records to a disposable test database."""
import argparse
import os
import re
import uuid
from pathlib import Path

from playwright.sync_api import sync_playwright, expect


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--frontend', default='http://localhost:3000')
    parser.add_argument('--allow-writes', action='store_true', required=True)
    parser.add_argument('--screenshots', type=Path)
    parser.add_argument('--channel', help='Use an installed browser, e.g. chrome or msedge')
    args = parser.parse_args()
    base = args.frontend.rstrip('/')
    marker = 'people-check-' + uuid.uuid4().hex
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(channel=args.channel)
        context = browser.new_context(viewport={'width': 1440, 'height': 1000})
        page = context.new_page()
        page.goto(base + '/admin/people')
        expect(page).to_have_url(re.compile('/admin/login'))
        page.locator('[name=username]').fill(os.environ['ADMIN_TEST_USERNAME'])
        page.locator('[name=password]').fill(os.environ['ADMIN_TEST_PASSWORD'])
        page.get_by_role('button', name='登录', exact=True).click()
        expect(page).to_have_url(base + '/admin')
        cookies = context.cookies(base + '/admin')
        session = next(cookie for cookie in cookies if cookie['httpOnly'])
        assert session['path'] == '/admin' and session['sameSite'] == 'Strict'
        page.goto(base + '/admin/people/new')
        page.locator('[name=display_name]').fill(marker)
        page.locator('[name=biography]').fill('浏览器验收资料')
        page.locator('[name=aliases]').fill('历史昵称一\n历史昵称二')
        page.get_by_role('button', name='创建人物', exact=True).click()
        expect(page).to_have_url(re.compile(r'/admin/people/\d+/edit'))
        person_id = re.search(r'/people/(\d+)', page.url).group(1)
        person_url = base + '/admin/people/' + person_id + '/edit'
        expect(page.locator('[name=aliases]')).to_have_value('历史昵称一\n历史昵称二')
        stale = context.new_page()
        stale.goto(person_url)
        page.locator('[name=biography]').fill('已修改的资料')
        page.get_by_role('button', name='保存人物资料', exact=True).click()
        expect(page.locator('[name=revision]')).to_have_value('2')
        stale.locator('[name=biography]').fill('保留未提交的输入')
        stale.get_by_role('button', name='保存人物资料', exact=True).click()
        expect(stale.get_by_role('alert')).to_be_visible()
        expect(stale.locator('[name=biography]')).to_have_value('保留未提交的输入')
        stale.close()
        page.goto(base + '/admin/midis/new')
        page.locator('[name=title]').fill(marker)
        page.locator('[name=slug]').fill(marker)
        page.get_by_role('button', name='创建档案', exact=True).click()
        expect(page).to_have_url(re.compile(r'/admin/midis/\d+/edit'))
        midi_id = re.search(r'/midis/(\d+)', page.url).group(1)
        page.locator('textarea[name=description]').fill('浏览器编辑验证')
        page.get_by_role('button', name='保存修改', exact=True).click()
        expect(page.locator('[name=revision]')).to_have_value('2')
        page.goto(base + '/admin/midis/' + midi_id + '/credits')
        page.get_by_role('button', name='添加署名', exact=True).click()
        while page.locator(f'[name=person_id] option[value="{person_id}"]').count() == 0:
            page.get_by_role('button', name='加载更多人物', exact=True).click()
            expect(page.get_by_role('button', name='保存署名', exact=True)).to_be_enabled()
        page.locator('[name=person_id]').select_option(person_id)
        page.locator('[name=role]').select_option('composer')
        page.get_by_role('button', name='保存署名', exact=True).click()
        expect(page.locator('[name=revision]')).to_have_value('3')
        expect(page.locator('[name=person_id]')).to_have_value(person_id)
        if args.screenshots:
            args.screenshots.mkdir(parents=True, exist_ok=True)
            page.screenshot(path=str(args.screenshots / 'credits-desktop.png'), full_page=True)
        page.set_viewport_size({'width': 390, 'height': 844})
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'credits-mobile.png'), full_page=True)
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile horizontal overflow'
        public = context.new_page()
        public.goto(base + '/midis/' + marker)
        expect(public.get_by_role('link', name=marker, exact=True)).to_be_visible()
        public.goto(base + '/people/' + person_id)
        expect(public.get_by_text('历史昵称一 / 历史昵称二', exact=True)).to_be_visible()
        expect(public.get_by_role('link', name=marker, exact=True)).to_be_visible()
        public.close()
        page.get_by_role('button', name=re.compile('移除第')).click()
        page.get_by_role('button', name='保存署名', exact=True).click()
        expect(page.locator('[name=revision]')).to_have_value('4')
        expect(page.locator('[name=person_id]')).to_have_count(0)
        history_url = base + '/admin/midis/' + midi_id + '/history'
        page.goto(base + '/admin/midis/' + midi_id + '/edit')
        page.get_by_role('link', name='管理来源与寻回 →', exact=True).click()
        expect(page).to_have_url(history_url)
        page.set_viewport_size({'width': 1440, 'height': 1000})
        page.get_by_role('button', name='新增历史来源', exact=True).click()
        expect(page.get_by_role('button', name='新增寻回记录', exact=True)).to_be_disabled()
        page.locator('[name=website_name]').fill('历史站点')
        page.locator('[name=original_url]').fill('https://example.org/test.mid')
        page.get_by_label('首次记录时间（UTC，可留空）').fill('2000-02-29T12:34:56.123')
        page.get_by_label('最后记录时间（UTC，可留空）').fill('1999-01-01T00:00')
        page.get_by_role('button', name='保存本条历史来源', exact=True).click()
        expect(page.locator('form').get_by_role('alert')).to_contain_text('首次记录时间不能晚于最后记录时间')
        expect(page.locator('[name=website_name]')).to_have_value('历史站点')
        page.get_by_label('最后记录时间（UTC，可留空）').fill('2001-01-01T00:00')
        page.locator('[name=notes]').fill('来源浏览器验收 ' + 'long-text-' * 80)
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'history-source-desktop.png'), full_page=True)
        page.set_viewport_size({'width': 390, 'height': 844})
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Source editor mobile overflow'
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'history-source-mobile.png'), full_page=True)
        page.get_by_role('button', name='保存本条历史来源', exact=True).click()
        expect(page.locator('[name=website_name]')).to_have_count(0)
        source_button = page.get_by_role('button', name=re.compile('编辑历史来源 历史站点'))
        source_button.click()
        source_id = page.locator('[name=record_id]').input_value()
        expect(page.locator('[name=first_seen_at]')).to_have_value('2000-02-29T12:34:56.123000')
        page.locator('[name=website_name]').fill('取消删除后保留')
        page.get_by_role('button', name='删除本条记录…', exact=True).click()
        page.get_by_role('button', name='取消删除，继续编辑', exact=True).click()
        expect(page.locator('[name=website_name]')).to_have_value('取消删除后保留')
        page.locator('[name=website_name]').fill('历史站点已编辑')
        page.get_by_role('button', name='保存本条历史来源', exact=True).click()
        expect(page.locator('[name=website_name]')).to_have_count(0)
        stale = context.new_page()
        stale.goto(history_url)
        stale.get_by_role('button', name=re.compile('编辑历史来源 历史站点已编辑')).click()
        expect(stale.locator('[name=record_id]')).to_have_value(source_id)
        stale.locator('[name=notes]').fill('并发冲突也要保留这段输入')
        page.get_by_role('button', name='新增寻回记录', exact=True).click()
        page.locator('[name=story]').fill('日期不详的寻回经过')
        page.locator('[name=evidence]').fill('寻回浏览器验收')
        page.get_by_role('button', name='保存本条寻回记录', exact=True).click()
        expect(page.locator('[name=story]')).to_have_count(0)
        stale.get_by_role('button', name='保存本条历史来源', exact=True).click()
        expect(stale.locator('form').get_by_role('alert')).to_contain_text('作品资料已被其他页面修改')
        expect(stale.locator('[name=notes]')).to_have_value('并发冲突也要保留这段输入')
        stale.close()
        page.get_by_role('button', name=re.compile(r'^编辑寻回记录 \d+$')).click()
        event_id = page.locator('[name=record_id]').input_value()
        expect(page.locator('[name=recovered_at]')).to_have_value('')
        expect(page.locator('[name=recovered_by]')).to_have_value('')
        page.get_by_role('button', name='刷新人物列表', exact=True).click()
        expect(page.locator('[name=recovered_by]')).to_be_enabled()
        # Load subsequent pages if this isolated DB already contains many fixtures.
        while page.locator(f'[name=recovered_by] option[value="{person_id}"]').count() == 0:
            page.get_by_role('button', name='加载更多人物', exact=True).click()
            expect(page.locator('[name=recovered_by]')).to_be_enabled()
        page.locator('[name=recovered_by]').select_option(person_id)
        page.get_by_label('寻回时间（UTC，可留空）').fill('2002-03-04T05:06:07.456')
        page.locator('[name=story]').fill('已核对的寻回经过')
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'history-event-mobile.png'), full_page=True)
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Event editor mobile overflow'
        page.get_by_role('button', name='保存本条寻回记录', exact=True).click()
        expect(page.locator('[name=story]')).to_have_count(0)
        public = context.new_page()
        public.goto(base + '/midis/' + marker)
        expect(public.get_by_text('历史站点已编辑', exact=True)).to_be_visible()
        expect(public.get_by_text('已核对的寻回经过', exact=True)).to_be_visible()
        expect(public.get_by_role('link', name=marker, exact=True)).to_be_visible()
        public.close()
        page.get_by_role('button', name=f'编辑寻回记录 {event_id}', exact=True).click()
        page.locator('[name=story]').fill('会话失效后仍保留')
        original_cookies = context.cookies(base + '/admin')
        context.clear_cookies()
        page.get_by_role('button', name='保存本条寻回记录', exact=True).click()
        expect(page.locator('form').get_by_role('alert')).to_contain_text('会话已过期')
        expect(page.locator('[name=story]')).to_have_value('会话失效后仍保留')
        expect(page.locator('[name=recovered_by]')).to_have_value(person_id)
        expect(page.locator('[name=recovered_at]')).to_have_value('2002-03-04T05:06:07.456000')
        context.add_cookies(original_cookies)
        page.get_by_label('寻回时间（UTC，可留空）').fill('')
        page.locator('[name=recovered_by]').select_option('')
        page.get_by_role('button', name='保存本条寻回记录', exact=True).click()
        expect(page.locator('[name=story]')).to_have_count(0)
        page.get_by_role('button', name=f'编辑寻回记录 {event_id}', exact=True).click()
        expect(page.locator('[name=recovered_at]')).to_have_value('')
        expect(page.locator('[name=recovered_by]')).to_have_value('')
        page.get_by_role('button', name='删除本条记录…', exact=True).click()
        page.get_by_role('button', name='确认永久删除本条记录', exact=True).click()
        expect(page.locator('[name=story]')).to_have_count(0)
        expect(page.get_by_role('button', name=f'编辑寻回记录 {event_id}', exact=True)).to_have_count(0)
        page.get_by_role('button', name=re.compile('编辑历史来源 历史站点已编辑')).click()
        page.get_by_role('button', name='删除本条记录…', exact=True).click()
        page.get_by_role('button', name='确认永久删除本条记录', exact=True).click()
        expect(page.locator('[name=website_name]')).to_have_count(0)
        expect(page.get_by_role('button', name=re.compile('编辑历史来源 历史站点已编辑'))).to_have_count(0)
        page.get_by_role('button', name='退出登录', exact=True).click()
        expect(page).to_have_url(re.compile('/admin/login'))
        page.goto(person_url)
        expect(page).to_have_url(re.compile('/admin/login'))
        browser.close()
    print('PASS: browser login/cookie, MIDI/people/credits/history CRUD, source dates, nullable recovery, deletion confirmation, 401/409 input retention, public pages, mobile width and logout')


if __name__ == '__main__':
    main()
